# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# 実行環境
executors:
  default:
    docker:
      - image: circleci/node:erbium # ジョブ実行環境のDockerイメージ(node 12.x)

# 再利用するstep
commands:
  npm_install:
    steps:
      - run:
          name: npm install
          command: npm install

jobs:
  build: # ジョブ名
    executor: # nameで使いたい実行環境を指定
      name: default
    steps:
      - checkout # ソースコードのチェックアウト
      - npm_install
      - run: # 順に実行したいコマンド
          name: build
          command: npm run build
      - run:
          name: unit test
          command: npm run test:unit
      - run:
          name: lint
          command: npm run lint

  deploy:
    executor:
      name: default
    steps:
      - checkout
      - npm_install
      - run:
          name: deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN


# Orchestrate or schedule a set of jobs
workflows:
  build_deploy: # ワークフローの名前
    # Run the welcome/run job in its own container
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master # masterブランチのみ